/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework;

import java.awt.Desktop;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dell
 */
public class BeverageInfo extends javax.swing.JFrame {

    private List<String[]> elements;
    private boolean clearTable = false;

    /**
     * Creates new form BeverageInfo
     */
    public BeverageInfo() {
        initComponents();
        ((SpinnerNumberModel) jPercentSpinner.getModel()).setMinimum(0);
        elements = new ArrayList<String[]>();
        jTable1.setAutoCreateRowSorter(true); // sorting of the rows on a particular column
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jAgeGroup1 = new javax.swing.JRadioButton();
        jAgeGroup2 = new javax.swing.JRadioButton();
        jID = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jBrandComboBox = new javax.swing.JComboBox<>();
        jAlcoholPercent = new javax.swing.JTextField();
        jCategoryComboBox = new javax.swing.JComboBox<>();
        jBtnAdd = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSearchCategoryCombo = new javax.swing.JComboBox<>();
        jBtnSearchByCategory = new javax.swing.JButton();
        jSearchPrice = new javax.swing.JTextField();
        jBtnSearchByPrice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnSearchByPercent = new javax.swing.JButton();
        jPercentSpinner = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jUserManual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(236, 100, 75));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("BEVERAGE INFORMATION SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Beverage ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beverage Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Beverage Category:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company/ Brand:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Suitable Age Group:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price:");

        jAgeGroup1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jAgeGroup1);
        jAgeGroup1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAgeGroup1.setForeground(new java.awt.Color(255, 255, 255));
        jAgeGroup1.setText("18 and above");

        jAgeGroup2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jAgeGroup2);
        jAgeGroup2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAgeGroup2.setForeground(new java.awt.Color(255, 255, 255));
        jAgeGroup2.setText("All Age Group");

        jID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIDKeyPressed(evt);
            }
        });

        jBrandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Brand", "Tuborg ", "CocaCola", "Red Bull", "Monster", "Old Durbar", "Red Label" }));

        jAlcoholPercent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAlcoholPercentKeyPressed(evt);
            }
        });

        jCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a category", "Soft Drink", "Energy Drink", "Hard Drink" }));

        jBtnAdd.setBackground(new java.awt.Color(34, 167, 240));
        jBtnAdd.setText("ADD");
        jBtnAdd.setBorder(new javax.swing.border.MatteBorder(null));
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnClear.setBackground(new java.awt.Color(34, 167, 240));
        jBtnClear.setText("CLEAR");
        jBtnClear.setBorder(new javax.swing.border.MatteBorder(null));
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Alcohol Percentage:");

        jPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPriceKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jAgeGroup2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAgeGroup1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jName)
                    .addComponent(jBrandComboBox, 0, 212, Short.MAX_VALUE)
                    .addComponent(jAlcoholPercent)
                    .addComponent(jPrice))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jBrandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jAgeGroup1)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgeGroup2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAlcoholPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(236, 100, 75));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel8.setText("BEVERAGE DETAILS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSearchCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a category", "Soft Drink", "Energy Drink", "Hard Drink" }));

        jBtnSearchByCategory.setBackground(new java.awt.Color(34, 167, 240));
        jBtnSearchByCategory.setText("Search By Category");
        jBtnSearchByCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchByCategoryActionPerformed(evt);
            }
        });

        jBtnSearchByPrice.setBackground(new java.awt.Color(34, 167, 240));
        jBtnSearchByPrice.setText("Search By Price");
        jBtnSearchByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchByPriceActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Beverage ID", "Beverage Name", "Beverage Category", "Company/Brand", "Age Group", "Price", "Alcohol%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jBtnSearchByPercent.setBackground(new java.awt.Color(34, 167, 240));
        jBtnSearchByPercent.setText("Search By Alcohol %");
        jBtnSearchByPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchByPercentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSearchCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jBtnSearchByCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(jSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jPercentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBtnSearchByPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSearchCategoryCombo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnSearchByCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnSearchByPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPercentSpinner)
                    .addComponent(jBtnSearchByPercent, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(44, 62, 80));
        jMenuBar1.setForeground(new java.awt.Color(44, 62, 80));

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setText("File");

        jMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuOpen.setText("Open File");
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuOpen);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenuHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuHelp.setText("Help");

        jUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jUserManual.setText("User Manual");
        jUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserManualActionPerformed(evt);
            }
        });
        jMenuHelp.add(jUserManual);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        if (clearTable) {
            elements.clear();
            clearTable = false;
        }
        String beverageID = jID.getText().trim();
        String beverageName = jName.getText().trim();
        String price = jPrice.getText().trim();
        String alcoholPercent = jAlcoholPercent.getText().trim();
        String age = "";
        String category = jCategoryComboBox.getSelectedItem().toString();
        String brand = jBrandComboBox.getSelectedItem().toString();

        if (jAgeGroup1.isSelected()) {
            age = jAgeGroup1.getText();
        }
        if (jAgeGroup2.isSelected()) {
            age = jAgeGroup2.getText();
        }

        if (!beverageID.isEmpty()) {
            if (!beverageName.isEmpty()) {
                if (jCategoryComboBox.getSelectedIndex() != 0) {
                    if (jBrandComboBox.getSelectedIndex() != 0) {
                        if (!age.isEmpty()) {
                            if (!price.isEmpty()) {
                                if (!alcoholPercent.isEmpty()) {
                                    String data[] = {beverageID, beverageName, category, brand, age, price, alcoholPercent};
                                    elements.add(data);
                                    String[] columNames = new String[]{
                                        "Beverage Id", "Beverage Name", "Beverage Category", "Company/Brand", "Suitable Age Group", "Price", "Alcohol Percentage"
                                    };
                                    Object[][] content = new Object[elements.size()][7];
                                    for (int i = 0; i < elements.size(); i++) {
                                        content[i][0] = elements.get(i)[0];
                                        content[i][1] = elements.get(i)[1];
                                        content[i][2] = elements.get(i)[2];
                                        content[i][3] = elements.get(i)[3];
                                        content[i][4] = elements.get(i)[4];
                                        content[i][5] = elements.get(i)[5];
                                        content[i][6] = elements.get(i)[6];
                                    }
                                    jTable1.setModel(new DefaultTableModel(content, columNames));
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "!! Please Enter Alcohol Percent !!", "", JOptionPane.WARNING_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "!! Please Enter the Price !!", "", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "!! Please Choose Suitable Age Group !!", "", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "!! Please Choose Brand !!", "", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "!! Please Choose Beverage Category !!", "", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "!! Please Enter Beverage Name !!", "", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "!! Please Enter Beverage ID !!", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:
        jID.setText("");
        jName.setText("");
        jCategoryComboBox.setSelectedIndex(0);
        jBrandComboBox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        jPrice.setText("");
        jAlcoholPercent.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIDKeyPressed
        // TODO add your handling code here:
        char pressedKey = evt.getKeyChar();
        int code = evt.getKeyCode();
        if (Character.isDigit(pressedKey) || code == 8) {
            jID.setEditable(true);
        } else if (code == 45) {
            jID.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Beverage ID cannot be negative !!", "", JOptionPane.WARNING_MESSAGE);
        } else {
            jID.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Only Integer values allowed !!", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jIDKeyPressed

    private void jPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPriceKeyPressed
        // TODO add your handling code here:
        char pressedKey = evt.getKeyChar();
        int code = evt.getKeyCode();
        if (Character.isDigit(pressedKey) || code == 8) {
            jPrice.setEditable(true);
        } else if (code == 45) {
            jPrice.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Price cannot be negative !!", "", JOptionPane.WARNING_MESSAGE);
        } else {
            jPrice.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Only Integer values allowed !!", "", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jPriceKeyPressed

    private void jAlcoholPercentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAlcoholPercentKeyPressed
        // TODO add your handling code here:
        char pressedKey = evt.getKeyChar();
        int code = evt.getKeyCode();
        if (Character.isDigit(pressedKey) || code == 8) {
            jAlcoholPercent.setEditable(true);
        } else if (code == 45) {
            jAlcoholPercent.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Alcohol Percentage cannot be negative !!", "", JOptionPane.WARNING_MESSAGE);
        } else {
            jAlcoholPercent.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "!! Only Integer values allowed !!", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jAlcoholPercentKeyPressed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserManualActionPerformed
        File file = new File("/resources/Help.pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "File not found");
        }
    }//GEN-LAST:event_jUserManualActionPerformed

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Select an csv or text file");
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV or Text file", "csv", "txt");
        jfc.addChoosableFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String filePath = jfc.getSelectedFile().getPath();
            try {
                if (filePath.endsWith(".csv")) {
                    populateFileToJTable(jfc.getSelectedFile(), "csv");
                    return;
                }
                populateFileToJTable(jfc.getSelectedFile(), "text");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jBtnSearchByCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchByCategoryActionPerformed
        search(jSearchCategoryCombo.getSelectedItem().toString());
    }//GEN-LAST:event_jBtnSearchByCategoryActionPerformed

    private void jBtnSearchByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchByPriceActionPerformed
        // TODO add your handling code here:
        int price;
        try {
            price = Integer.parseInt(jSearchPrice.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "***** Insert integer number only ***** ", "", JOptionPane.WARNING_MESSAGE);
            return;
        }
        List<Integer> searchArray = new ArrayList<>();
        for (int i = 0; i < elements.size(); i++) {
            String el[] = elements.get(i);
            searchArray.add(Integer.parseInt(el[5]));
        }
        Integer array[] = new Integer[searchArray.size()];
        array = searchArray.toArray(array);
        int selectedIndex = binarySearch(price, selectionSort(array));
        if (selectedIndex == -1) {
            showErrorMessage("Price Not found !!!");
            return;
        }
        sortTable(5);
        JOptionPane.showMessageDialog(rootPane, "***** First Matching Beverage Details *****\n"
                + "Beverage Id:" + jTable1.getValueAt(selectedIndex, 0) + "\n"
                + "Beverage Name:" + jTable1.getValueAt(selectedIndex, 1) + "\n"
                + "Beverage Category:" + jTable1.getValueAt(selectedIndex, 2) + "\n"
                + "Company/Brand:" + jTable1.getValueAt(selectedIndex, 3) + "\n"
                + "Suitable Age Group:" + jTable1.getValueAt(selectedIndex, 4) + "\n"
                + "Price:" + jTable1.getValueAt(selectedIndex, 5) + "\n"
                + "Alcohol Percentage:" + jTable1.getValueAt(selectedIndex, 6) + "\n",
                "", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jBtnSearchByPriceActionPerformed

    private void jBtnSearchByPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchByPercentActionPerformed
        Integer percentage = (Integer) jPercentSpinner.getValue();
        List<Integer> searchArray = new ArrayList<>();
        for (int i = 0; i < elements.size(); i++) {
            String el[] = elements.get(i);
            searchArray.add(Integer.parseInt(el[6].replace("%", "")));
        }
        Integer array[] = new Integer[searchArray.size()];
        array = searchArray.toArray(array);
        int selectedIndex = binarySearch(percentage, selectionSort(array));
        if (selectedIndex == -1) {
            showErrorMessage(" Not found !!!");
            return;
        }
        sortTable(6);
        JOptionPane.showMessageDialog(rootPane, "***** First Matching Beverage Details *****\n"
                + "Beverage Id:" + jTable1.getValueAt(selectedIndex, 0) + "\n"
                + "Beverage Name:" + jTable1.getValueAt(selectedIndex, 1) + "\n"
                + "Beverage Category:" + jTable1.getValueAt(selectedIndex, 2) + "\n"
                + "Company/Brand:" + jTable1.getValueAt(selectedIndex, 3) + "\n"
                + "Suitable Age Group:" + jTable1.getValueAt(selectedIndex, 4) + "\n"
                + "Price:" + jTable1.getValueAt(selectedIndex, 5) + "\n"
                + "Alcohol Percentage:" + jTable1.getValueAt(selectedIndex, 6) + "\n",
                "", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jBtnSearchByPercentActionPerformed

    private void showErrorMessage(String message) {
        JOptionPane optionPane = new JOptionPane(message, JOptionPane.ERROR_MESSAGE);
        JDialog dialog = optionPane.createDialog("Failure");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    private void sortTable(int sortIndex) {
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        int columnIndexToSort = sortIndex;
        sortKeys.add(new RowSorter.SortKey(columnIndexToSort, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
        sorter.sort();
    }

    private void search(String searchValue) {
        int counter = 0;
        List<String> searchArray = new ArrayList<>();
        for (int i = 0; i < elements.size(); i++) {
            String el[] = elements.get(i);
            searchArray.add((el[2]));
        }
        String array[] = new String[searchArray.size()];
        array = searchArray.toArray(array);
        Arrays.sort(array);
        for (int i = 0; i < array.length; i++) {
            int index = binarySearch(array, searchValue);
            if (index != -1) {
                counter++;
                searchArray.remove(index);
                array = searchArray.toArray(new String[searchArray.size()]);
            }
        }
        JOptionPane.showMessageDialog(rootPane, "***** Found " + counter + " beverages in list ***** " + filter(searchValue, 2), "", JOptionPane.WARNING_MESSAGE);
    }


    private int binarySearch(int search, Integer[] array) {

        int start = 0;
        int end = array.length - 1;

        while (start <= end) {

            int middle = (start + end) / 2;

            if (search < array[middle]) {
                end = middle - 1;
            }

            if (search > array[middle]) {
                start = middle + 1;
            }

            if (search == array[middle]) {
                return middle;
            }
        }
        return -1;

    }

    private Integer[] selectionSort(Integer[] arr) {
        for (int i = 0; i < arr.length - 1; i++) {
            int index = i;
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[j] < arr[index]) {
                    index = j;
                }
            }
            int smallerNumber = arr[index];
            arr[index] = arr[i];
            arr[i] = smallerNumber;
        }
        return arr;
    }

    private String filter(String searchValue, int index) {
        String beverageList = "";
        for (int i = 0; i < elements.size(); i++) {
            String el[] = elements.get(i);
            if (el[index].equals(searchValue)) {
                beverageList = beverageList + "\n" + (el[1]);
            }

        }
        return beverageList;
    }

    public void populateFileToJTable(File file, String type) throws FileNotFoundException, IOException {
        clearTable = true;
        elements.clear();
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line = null;
        while ((line = br.readLine()) != null) {
            String splitted[];
            if (type.equals("csv")) {
                splitted = line.split(",");
            } else {
                splitted = line.split("~");
            }
            elements.add(splitted);
        }
        br.close();
        String[] columNames = new String[]{
            "Beverage Id", "Beverage Name", "Beverage Category", "Company/Brand", "Suitable Age Group", "Price", "Alcohol Percentage"
        };
        Object[][] content = new Object[elements.size()][7];
        for (int i = 0; i < elements.size(); i++) {
            content[i][0] = elements.get(i)[0];
            content[i][1] = elements.get(i)[1];
            content[i][2] = elements.get(i)[2];
            content[i][3] = elements.get(i)[3];
            content[i][4] = elements.get(i)[4];
            content[i][5] = new Integer(elements.get(i)[5]);
            content[i][6] = new Integer(elements.get(i)[6]);
        }
        jTable1.setModel(new DefaultTableModel(content, columNames) {
            Class[] types = {String.class, String.class, String.class,
                String.class, String.class, Integer.class, Integer.class};

            @Override
            public Class getColumnClass(int columnIndex) {
                return this.types[columnIndex];
            }

        });
    }

    private int binarySearch(String[] arr, String x) {
        int l = 0, r = arr.length - 1;
        while (l <= r) {
            int m = l + (r - l) / 2;
            int res = x.compareTo(arr[m]);
            if (res == 0) {
                return m;
            }
            if (res > 0) {
                l = m + 1;
            } else {
                r = m - 1;
            }
        }
        return -1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeverageInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeverageInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeverageInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeverageInfo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeverageInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jAgeGroup1;
    private javax.swing.JRadioButton jAgeGroup2;
    private javax.swing.JTextField jAlcoholPercent;
    private javax.swing.JComboBox<String> jBrandComboBox;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnSearchByCategory;
    private javax.swing.JButton jBtnSearchByPercent;
    private javax.swing.JButton jBtnSearchByPrice;
    private javax.swing.JComboBox<String> jCategoryComboBox;
    private javax.swing.JTextField jID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jPercentSpinner;
    private javax.swing.JTextField jPrice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSearchCategoryCombo;
    private javax.swing.JTextField jSearchPrice;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jUserManual;
    // End of variables declaration//GEN-END:variables
}
